### ISSUE TITLE
Improve the build system to support both ESM/CJS modules

### ISSUE THREAD

**Issue by antonioru** [urpflanze-org/urpflanze#10]
The NPM package should export both CJS/ESM modules as well as the types definition so that:

- Will be possibile to import only the involved modules
- Will be easier for tools like webpack to perform three-shaking
- Will be possible to test single modules as a javascript compiled files.

**Comment by genbs** [comment]
I modified the building system and added the compilation in ESM, CJS and UMD in version ^1.0.0
