### ISSUE TITLE
How can I start drawing shapes from left top instead of center?

### ISSUE THREAD

**Issue by escobar5** [urpflanze-org/urpflanze#12]
I tried with anchor in Scene, but nothing seems to change:

https://jsfiddle.net/zL36g9f8/

**Comment by genbs** [comment]
I had introduced the concept of anchor on [Core](https://github.com/urpflanze-org/core) ([c82469f](https://github.com/urpflanze-org/core/commit/c82469f4d6cc500e4212db75ecd7d52cd0d1d878)), now I also added it to the shapes ([8beeb43](https://github.com/urpflanze-org/core/commit/8beeb43a1a6fddccab8153bdd844dd07623d3252))

Unfortunately I still do not bring the changes in the javascript library for browsers, in the meantime you can try here using the [Core](https://github.com/urpflanze-org/core) and [Drawer](https://github.com/urpflanze-org/drawer-canvas)

https://jsfiddle.net/8u7wpem0/
