### ISSUE TITLE
Links to old location of docs still present

### ISSUE THREAD

**Issue by doersino** [urpflanze-org/urpflanze#9]
Just a quick heads up to let you know that the link in the "About" section of the repo on GitHub still points to https://genbs.github.io/urpflanze/ instead of https://urpflanze.org/urpflanze/, as do the two "Full docs and Examples" links in `README.md`. It's possible that there are other instances, I haven't checked exhaustively.

(Excuse my ignoring the issue template – I felt like it didn't apply in this situation.)

**Comment by doersino** [comment]
Had a brain fart and forgot about code search for a minute – in fact, there are a couple more instances: https://github.com/urpflanze-org/urpflanze/search?q=genbs.github.io

**Comment by genbs** [comment]
Thank you for reporting, I'm doing a refactoring and I have overshadowed those changes. 
I just fixed it :)
